# config.yaml

db:
  username: "ramaprakoso"
  password: "Pinguin2023!@#"
  host: "103.179.33.234"
  port: "3306"
  name: "db_baas"

rabbitmq:
  url: "amqp://tarsius-user:dgWj5KqPC5A05Y3k0V5Q0@103.179.33.39:31057/"

tcp:
  url: "0.0.0.0:8082"

redis:
  host: "localhost:6379"
  password: ""
  db: 1

